# This is a basic workflow to help you get started with Actions

name: bump-version

# Controls when the workflow will run
on: 
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: bump-version
        run: |
          git config user.name "Version Bumper"
          git config user.email "vbump@stratosphere.studios"
          BRANCH="$(git branch --show-current)"
          COMMIT="$(git rev-list --count ${BRANCH})"
          echo "Branch: ${BRANCH}\nCommit: ${COMMIT}" >| version.txt
          git add version.txt
          git commit -m "Auto version bump"
          git push
