# This is a basic workflow to help you get started with Actions

name: bump-version

# Controls when the workflow will run
on: 
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      # Runs a set of commands using the runners shell
      - name: bump-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH="$(git branch --show-current)"
          COMMIT="$(git rev-list --count HEAD)"
          echo "Branch: ${BRANCH}\\nComcfbnfvgbnmit: ${COMMIT}" >| version.txt
          git commit -m "Auto version bump" -a
          git push
